### ISSUE TITLE
Publish a standalone exe

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps-cli#241]
Just a discussion to see if this is possible for now. No need to implement yet.

**Is your feature request related to a problem? Please describe.**
Investigating using the CLI for debugging SWAs in Visual Studio. Instead of installing the Node toolchain, VS would like to acquire the CLI as an exe on Windows.

**Describe the solution you'd like**
Publish the CLI as standalone exe (Windows, perhaps also macOS for VS for Mac). Use [pkg](https://www.npmjs.com/package/pkg)? Perhaps publish to GitHub releases?

**Describe alternatives you've considered**
Install the Node toolchain in VS. They would rather not do this.

**Additional context**

**Comment by horihiro** [comment]
This is a tiny concern when the standalone version is published.

It is appropriate to change the message `Run npm i @azure/static-web-apps-cli to update` in the following notice because the standalone exe may not be able to be updated by the `npm install`.

```
         ╭────────────────────────────────────────────────────╮
         │                                                    │
         │          Update available a.b.c → x.y.z            │
         │   Run npm i @azure/static-web-apps-cli to update   │
         │                                                    │
         ╰────────────────────────────────────────────────────╯
```
But I'm not sure if the message can be changed.

Or it is good also to disable the updater by the value `process.argv[0]` or something which can judge if the CLI process is invoked from `node` or standalone.

**Comment by anthonychu** [comment]
Thanks. That’s definitely something we’ll need to check for if we decide to do this.
