### ISSUE TITLE
Show http://localhost:4280 as the main emulator URL

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps-cli#242]
**Is your feature request related to a problem? Please describe.**
Currently, this is printed on startup:

```
[swa] Available on:
[swa]     http://0.0.0.0:4280
[swa]     http://192.168.187.166:4280
```

**Describe the solution you'd like**
Not sure how often those addresses are used. I'd imagine 99% of the time, we want folks to use http://localhost:4280. Consider changing this output to simply:

```
[swa] Available on: http://localhost:4280
```

Or remove it altogether and just add the URL to this message: 

```
Azure Static Web Apps emulator started at http://localhost:4280 . Press CTRL+C to exit.
```

**Comment by diberry** [comment]
Without this, Azure Active Directory redirects while developing locally won't work at first glance because they don't allow http for anything but localhost. And if I try to use the urls listed in the SWA CLI, then I have to make sure locally I'm running with HTTPS. A customer has to really get AD and the client app to know what to change where.

**Comment by manekinekko** [comment]
@diberry for your particular use case, there is a `--host` and `--port` options to help you change the CLI default address and port:

`swa start --host localhost --port 1234`

![image](https://user-images.githubusercontent.com/1699357/122520989-97d25780-d014-11eb-92bb-c4fb03b46662.png)

**Comment by diberry** [comment]
@manekinekko That is only a fix if the client spins up with HTTPS too. Is there a flag for that? I don't have a certificate, I usually have the .env in React have https=true. 

The issue is that if I want AAD to redirect to anything other than the literal "localhost", it has to be https. So an IP address has to be able to handle HTTPS. 

![image](https://user-images.githubusercontent.com/41597107/122583707-69ea1480-d00e-11eb-8c77-2d09b683b31e.png)

**Comment by manekinekko** [comment]
You can enable SSL using the [`--ssl`](https://github.com/Azure/static-web-apps-cli#configuration) flag, however, for now you need to generate your own SSL certificate. The CLI does ship with its own SSL certificate for localhost (see https://github.com/Azure/static-web-apps-cli/tree/main/scripts). But for now we do required the users have their own SSL.

@anthonychu we may need to improve the SSL experience.

**Comment by anthonychu** [comment]
> anything other than the literal "localhost"

Does this mean `http://localhost` works? If that’s true, you can get the CLI to start up at port 80.

**Comment by manekinekko** [comment]
> ... you can get the CLI to start up at port 80.

But then you will have to start the CLI as an administrator (or with root). because that's a limitation of the operating system.
