### ISSUE TITLE
CSS part of Vue app is not rendered on dev server

### ISSUE THREAD

**Issue by k-miyake** [Azure/static-web-apps-cli#339]
**Describe the bug**
The `<style>` part of  SFC(Single File Component) is not rendered when launching Vue App using SWA CLI via dev server.

**To Reproduce**
1. Create a new Vue app with `npm init vite@latest my-vue-app --template vue`
2. `cd my-vue-app && npm i`
4. Type in command `swa start http://localhost:3000 --run "npm run dev"`
5. Click on http://localhost:4280
6. Displaying HTML that does not reflect CSS written in `<style>` of `App.vue` (e.g. not centered)

**Expected behavior**
The HTML with CSS is displayed as if it was started on the native dev server.

**Screenshots**

Start with SWA CLI (`http://localhost:4280'`)

<img width="700" alt="swa-cli-4280" src="https://user-images.githubusercontent.com/1104403/141682426-64e0112c-4957-4760-bb1e-e6c92d99952a.png">

Start with Vite dev server (`http://localhost:3000`)

<img width="948" alt="swa-cli-3000" src="https://user-images.githubusercontent.com/1104403/141682435-77eecc89-bbd5-4c73-87bd-d5bb29f82ef2.png">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version [95.0.4638.69]

**Additional context**
If run it from static files after build, like `swa start dist`, it will be rendered correctly.

**Comment by manekinekko** [comment]
Hey @k-miyake can you please share a screenshot of the network/console tabs from the browser's devtool?

**Comment by k-miyake** [comment]
@manekinekko Here is a screenshot of the network/console tabs.
![swa-cli-4280-network](https://user-images.githubusercontent.com/1104403/141970747-b698f5d0-a24d-4887-9ed5-74ac992638cd.png)

![swa-cli-4280-console](https://user-images.githubusercontent.com/1104403/141970772-c973aa8f-5e0c-498c-91ae-445172d2520d.png)

**Comment by manekinekko** [comment]
Looks like this issue is caused by #346

**Comment by LHousehold** [comment]
I'm also experiencing this issue using Vite and SvelteKit. Due to another issue described [here](https://twitter.com/LHousehold/status/1463172755596234753), I had to temporarily downgrade to 0.8.0 to get to this point. I thought I'd bring it up because it sounds very similar to what's happening here.

I created a repo to recreate the issue: https://github.com/LHousehold/example-issue-azure-swa-sveltekit

The repo's readme describes the issue, but basically it seems like the file with the relevant CSS is not being loaded because Vite uses query params which route to different content.

http://localhost:3000/src/routes/index.svelte?svelte&type=style&lang.css
When accessed directly and working correctly, the above returns different content than the below, as if they are completely different files.
http://localhost:3000/src/routes/index.svelte

But when using the cli with port 4280, these two paths both return only the content from /index.svelte without the query params. I suspect k-miyake is facing a similar issue.

**Comment by k-miyake** [comment]
I think the issue @LHousehold reported with SvelteKit is the same issue I'm having, which is caused by Vite's dev server not reading the CSS correctly when started on port 4280 of the SWA CLI.

**Comment by k-miyake** [comment]
@manekinekko I have confirmed that this has been fixed in SWA CLI 0.8.2. Thank you for your support.

**Comment by SteveVaneeckhout** [comment]
I'm having the same problem as @k-miyake with version 0.8.3 when using Vite and Vue.

**Comment by manekinekko** [comment]
We have fixed this issue in the next release. Will schedule a release soon.
