### ISSUE TITLE
Unable to start with Microsoft Learn sample

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps-cli#45]
**Describe the bug**

Unable to use with the MSLearn sample.

**To Reproduce**

```bash
git clone https://github.com/MicrosoftDocs/mslearn-staticwebapp-api.git
cd mslearn-staticwebapp-api/
cd react-app/
npm i
npm run build
cd ..
```

Can't find the API:

```bash
swa --app-location react-app/build --api-location api-starter --api-prefix api
WARNING: SWA configuration not found.
>> detected runtime: unknown
[auth] Auth server listening on http://127.0.0.1:4242
[ api] No API found. Skipping.
[ app] Starting up http-server, serving /Users/antchu/source/temp/mslearn-staticwebapp-api/
[ app] Available on:
[ app]   http://127.0.0.1:4200
[ app]   http://192.168.187.204:4200
[ app]   http://192.168.187.218:4200
[ app] Unhandled requests will be served from: http://0.0.0.0:80/?
[ app] Hit CTRL-C to stop the server
[ api] ([ -d '/Users/antchu/source/temp/mslearn-staticwebapp-api/api' ] && (cd /Users/antchu/source/temp/mslearn-staticwebapp-api/api; func start --cors *)) || echo 'No API found. Skipping.' exited with code 0
[ swa] >> SWA listening on 0.0.0.0:80
```

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by anthonychu** [comment]
@manekinekko Could you please take a look at this? Would like to use this as the sample app to provide the VS Code folks to work on integrating debugging. Thanks.

**Comment by manekinekko** [comment]
@anthonychu I have this issue on my todo list for this week. 

In the meantime, I am noticing that t[he API does not expose any GET](https://github.com/MicrosoftDocs/mslearn-staticwebapp-api/tree/main/api-starter) method for listing products. Is that the expected behavior?

cc @johnpapa

**Comment by johnpapa** [comment]
@manekinekko  -  The repo @anthonychu  is pointing to is the starting point for the learn module. So the GET API is not there yet, the learner will add it.

I noticed that `react-app` was chosen, yet the port is `4200`. This is not the matching port that React is using in the github example. Not sure if that matters ... as it may just be the 4200 that the emulator is using and proxying the rest. But wanted to point it out

I have not been able to get the emulator/cli to work with monorepos like this. Looking forward to these changes! Thanks

**Comment by manekinekko** [comment]
Thank you @johnpapa 

You are right about port `4200`, it is only the used internally by the static server of the cli. I know this might be confusing so I am gonna change all ports and use something different. Any suggestions?

When it comes to monorepo support, it's being tracked in this [other issue](https://github.com/Azure/swa-emulator/issues/32). Would love to have your thoughts about this topic there if you have some time.

**Comment by johnpapa** [comment]
@manekinekko perhaps just choose a port that is not one of the Vue, React, or Angular ones. Any port should be fine

**Comment by manekinekko** [comment]
@anthonychu here is how you can *temporarily* launch the learn module example:

- clone branch #41 which adds support for selecting arbitrary folders + start sub command
- as @johnpapa  mentioned you need to update the learn example and add the `GET /products` API. I did something dirty like this:
```javascript
module.exports = async function (context, req) {
  context.res.status(200).json(require('../shared/product-data').getProducts());
};
```
- then run the new swa command: `swa start react-app/build --api api-starter` (see discussion #26)
- then access the default URL `http://localhost` and you should access the working app
- I did a quick test, all CRUD operations are working as expected.

![image](https://user-images.githubusercontent.com/1699357/105362603-60918300-5bfb-11eb-9333-3e7b79abc925.png)


Let me know if you are still blocked. I hope we'll have a working release pipeline soon so we can publish alpha packages instead of having to go through all these steps again!

**Comment by manekinekko** [comment]
@anthonychu this issue should be fixed in `main` . Feel free to close it.
