### ISSUE TITLE
Display Azure AD tenant name in tenant picker

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps-cli#513]
**Is your feature request related to a problem? Please describe.**
Currently, when using `swa login`, it displays a list of tenant id's in a picker. Can it also include the tenant name?

**Comment by Timothyw0** [comment]
Closing this issue as it has been done in this commit: https://github.com/Azure/static-web-apps-cli/commit/a2ee6768bb6f8dcace5b0f99643e152580f68682

Running swa login using the latest version shows subscription names in the picker rather than id's. Please feel free to re-open or submit a new issue if I am mistaken!
