### ISSUE TITLE
navigationFallback not working with long query string

### ISSUE THREAD

**Issue by niekbridge** [Azure/static-web-apps-cli#520]
**Describe the bug**
When a long query string parameter value is passed the fallback route won't load.

I am getting a Microsoft security token in the query parameter, which I presume is too long for Azure Static Web App to handle. The fallback is correctly served after removing characters from the returned value. This leads me to believe there is a character limit on the query string.

**To Reproduce**

1. Go to https://witty-mud-0d3ad8410.1.azurestaticapps.net/
2. Add a very long query parameter
3. Hit enter

**Expected behavior**
Full query string passed and correct fallback route served

**Screenshots**
<img width="397" alt="Screenshot 2022-06-13 at 14 15 04" src="https://user-images.githubusercontent.com/78557728/173361956-319c870d-edcd-430a-ba40-28648e9ac5f4.png">

**Comment by sgollapudi77** [comment]
Hey @niekbridge, yes we do have limit on the Url length and query length. The max URL length is 8192, and the max query string length is 4096.
Also, since this issue is not related to SWA_CLI we're closing this now. But please look into this [issue](https://github.com/Azure/static-web-apps/issues/848) for reference.
