### ISSUE TITLE
Emulate routes config

### ISSUE THREAD

**Issue by manekinekko** [Azure/static-web-apps-cli#6]
Checkout [docs](https://docs.microsoft.com/azure/static-web-apps/routes) for more details.

**Comment by aaronpowell** [comment]
With #11 I've implemented a first-pass on supporting this.

When the proxy starts up it'll look for a `routes.json` file in the `app_artifact_location`, and if it exists it'll load those routing rules into the proxy server. Then, when a request comes in, the proxy server will check if the route matches a rule. If a rule is found, the app which check what the rule states (access control, redirect or status code response), and then apply what the rule states.

**Comment by aaronpowell** [comment]
There's still a few outstanding things:

- [ ] [Custom error pages](https://docs.microsoft.com/en-gb/azure/static-web-apps/routes?WT.mc_id=-github-wachegha#custom-error-pages)
- [ ] [Custom mime types](https://docs.microsoft.com/en-gb/azure/static-web-apps/routes?WT.mc_id=-github-wachegha#custom-mime-types)
- [ ] [Default headers](https://docs.microsoft.com/en-gb/azure/static-web-apps/routes?WT.mc_id=-github-wachegha#default-headers)
- [ ] [Redirects](https://docs.microsoft.com/en-gb/azure/static-web-apps/routes?WT.mc_id=-github-wachegha#redirects) (it won't send the right status code response)

**Comment by anthonychu** [comment]
With the new unified config file coming, perhaps we should pivot and support that instead of routes.json.

Also would be great if the emulator can search for the config file, starting from the app_location. Perhaps add an additional command line flag to specify the location of the file, as this info may not be available when starting using something like `--use-app`.

@mkarmark can provide info on the routing, fallback, and response overrides logic in the new config file.

**Comment by manekinekko** [comment]
Notes from today's meeting:
- idea: we could publish the route engine as a binary and do a function call from within the CLI.
