### ISSUE TITLE
GOT dependency vulnerability

### ISSUE THREAD

**Issue by ottoville** [Azure/static-web-apps-cli#684]
The SWA-CLI have dependency of  GOT 9.6.0 package as seen in following diagram:

└─┬ @azure/static-web-apps-cli@1.1.1
  └─┬ update-notifier@5.1.0
    └─┬ latest-version@5.1.0
      └─┬ package-json@6.5.0
        └── got@9.6.0
        
The GOT package version before 12.1.0 have vulnerability CVE-2022-33987 https://nvd.nist.gov/vuln/detail/CVE-2022-33987

**Comment by fgoulet** [comment]
I'd like to see this vulnerability addressed sometime also.

**Comment by dylan-smith** [comment]
this is annoying, it's giving my project that uses the CLI package a security alert in github because of this, with no apparent way to address it short of getting rid of my reliance on the SWA CLI.

![image](https://github.com/Azure/static-web-apps-cli/assets/1508559/4a8a7c6b-2600-47b1-bb0f-14a8f71606be)

**Comment by nkelly75** [comment]
This is still an issue with `@azure/static-web-apps-cli@1.1.4`

**Comment by adrianhall** [comment]
WIP: This is a problem with update-notifier, which has had a PR since early last year for this CVE with no action.

Will investigate switching to alternate libraries, or maybe just including a simplified version in our CLI.
