### ISSUE TITLE
Old Data API builder version used

### ISSUE THREAD

**Issue by itpropro** [Azure/static-web-apps-cli#806]
The current implementation for the Data API builders seems to pull the latest version specified by this metadata url: https://go.microsoft.com/fwlink/?linkid=2226493.
This points to 0.9.7, not to the latest version 0.10.23 of the Data API builder. 
I think the CLI should resolve the latest version based on the GitHub releases url (`https://github.com/Azure/data-api-builder/releases/latest`) that points to the latest release instead of relying on an internal link shortener/redirection service like go.microsoft.com.

**Comment by cjk7989** [comment]
Thanks for reporting that. WIll update the link and your advise is very helpful.

**Comment by itpropro** [comment]
> Thanks for reporting that. WIll update the link and your advise is very helpful.

Any updates on this? As there are so many bugs in the old version, I have to manually overwrite 0.9.7 currently to make it work on most projects.

**Comment by MrMossevig** [comment]
@itpropro We have the same issues - how do you “overwrite” the version number?

**Comment by itpropro** [comment]
Nice to see you taking over @Timothyw0 ! Would be great if you could look into this issue as well as #791 and #756.
Great to see the cli getting some love again, looking forward to support with PRs :)

**Comment by MrMossevig** [comment]
Thank you @Timothyw0 !

Did you solve the issue in a future proof manner, so there is some transparency as to when new versions of the api will be propagated to SWA? Or will it continue to be updated on an ad-hoc basis?

**Comment by Timothyw0** [comment]
@MrMossevig Unfortunately the link forwarding of our DAB Release Metadata URL is managed by another internal team so that is done at an ad-hoc basis. We are being asked to stay on the same version other SWA components are currently using. 

If there ever is a blocker like this again, the workaround would be to overwrite that Metadata URL until all of SWA gets the green light to update to a newer DAB API version. Hope this helps! 😄
