### ISSUE TITLE
Runs dotnet run when I don't want it to

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps-cli#91]
**Describe the bug**
Detects .NET and runs build but I don't want it to do that.

**To Reproduce**
1. In a folder that has a .csproj file, start the cli for another folder that contains static assets. For example: `swa start static`
2. It thinks it's dotnet and runs dotnet run.

**Expected behavior**
It shouldn't run any kind of build, especially since the folder I'm passing to the CLI isn't even a dotnet app. Even if the folder is a dotnet app, should we automatically do dotnet run or just serve it like static files? I think the expectation is to serve static files. If we want an automatic build, maybe pass a flag.

**Comment by manekinekko** [comment]
That's weird. I can't reproduce this issue locally.
![image](https://user-images.githubusercontent.com/1699357/109370700-c085e400-78a1-11eb-8dc4-d3d2c5b597ed.png)

@aaronpowell would you mind giving this issue a shot on your Windows setup?

**Comment by aaronpowell** [comment]
@manekinekko your test is unlikely to trigger as a dotfile returns `''` for `path.extname`, as per: https://nodejs.org/api/path.html#path_path_extname_path

The problem is that the first test is for a `csproj` file, in https://github.com/Azure/static-web-apps-cli/blob/main/src/core/runtimes.ts#L18, and this is triggered by https://github.com/Azure/static-web-apps-cli/blob/main/src/cli/commands/start.ts#L92 and it's using the `appLocation` not the `appArtifactLocation` to detect the runtime.

I'll send a PR to fix.

**Comment by aaronpowell** [comment]
Now that I've done some proper diagnostics of the problem, it's a little more complicated than I'd hoped.

The issue is rooted in the fact that with Blazor support we run the `dotnet watch` command, so you can edit the stuff and it'll recompile without you needing to run additional commands. This is a big of a divergence from how we do JavaScript apps, because if, say, it's a React app, unless you're providing the server address, it won't run webpack (or whatever) on your behalf with each file change.

So, while you might say "run from the `static` folder" the runtime detector will ignore that and look at the `appLocation` (which in this case is `/`, and it finds a `csproj` there so goes "well, must be a .NET app", even though you're wanting to serve static assets.

This comes to the question then of how someone would expect the cli to work. If I was to run `swa start static` are we going to just ignore everything about the environment and run a HTTP server in the `static` folder, or would we expect the underlying runtime to be tasked with setting up the HTTP server? (`dotnet watch run <Blazor App>` or our own node server)

I think we need to look at the usage workflow of the cli to understand the way someone would be using it to get an idea of _what's right_.

**Comment by anthonychu** [comment]
I think we need to think about whether we want to magically run dotnet watch (or npm start) here. I vote for not doing anything like this automatically.

is this behaviour documented anywhere?

**Comment by aaronpowell** [comment]
No, it's not likely documented somewhere, that's crazy talk! 🤣

I agree we want to avoid "magic things" happening, and that's why I think we need to look at the scenarios of a user. If I clone a Blazor SWA that uses the cli so I can do auth, what should happen when I hit `F5` in VS Code?

**Comment by anthonychu** [comment]
This still needs to be investigated and discussed with @nturinski @fiveisprime @ejizba. Hoping there's a gesture like the "initialize project" in the Functions extension that can prompt the customer for information to set up their launch config. Something like this:

https://github.com/anthonychu/swa-cli-js-sample/blob/150b4d06b988b48eb7ca26362b65336657111464/.vscode/launch.json

Except for Blazor, replace the Edge thing with what's documented [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-5.0&tabs=visual-studio-code#vscode).

I'll be working on the Blazor version of the launch config this week to see what it would look like.

**Comment by manekinekko** [comment]
@anthonychu  what's the status of this issue?

**Comment by anthonychu** [comment]
It no longer does the magic which is good. Still need to figure out how to set up F5 debug in VS Code.
